### PR TITLE
Progress on supporting IPv6

### LINKED ISSUE #804: Node 18 support
`yarn test` with Node 18:

```
Suites:   ​53 passed​, ​53 of 54 completed​
Asserts:  ​​​3 failed​, ​2774 passed​, ​of 2777​
```

### PR DESCRIPTION
**Pull request by MaxLeiter**
Resolves #804

### CODE REVIEW

File: lib/server.js [hunk 1]
```diff
@@ -508,7 +508,15 @@ Object.defineProperties(Server.prototype, {
...
         str = 'ldap://'
       }
-      str += this.host + ':' + this.port
+
+      let host = this.host
+      // Node 18 switched family from returning a string to returning a number
+      // https://nodejs.org/api/net.html#serveraddress
+      if (addr.family === 'IPv6' || addr.family === 6) {
+        host = '[' + this.host + ']'
+      }
```
Comment (jsumners) [inline lib/server.js:517]: We need a test to check for IPv6 connectivity. Since we don't yet have v18 in the testing matrix, we don't need to cover the branch. I don't want to add v18 to the testing matrix until I can cut the next major release.

**Review by jsumners — CHANGES_REQUESTED** [review]

**Comment by MaxLeiter** [comment]
Marking this as ready as tests pass locally

**Review by UziTech — APPROVED** [review]

**Comment by jsumners** [comment]
> Marking this as ready as tests pass locally

It is missing the test requested in https://github.com/ldapjs/node-ldapjs/pull/805#discussion_r887929827

File: lib/server.js (hunk 1 above)
Comment (jsumners) [reply lib/server.js:517]: @MaxLeiter are you able to add this test?

Comment (MaxLeiter) [reply lib/server.js:517]: Yeah sorry, I misunderstood what you meant by “dont need to cover this test”

Comment (MaxLeiter) [reply lib/server.js:517]: Test pushed. Lmk if that's what you meant.

Comment (MaxLeiter) [reply lib/server.js:517]:
```
Suites:   ​54 passed​, ​54 of 54 completed​
Asserts:  ​​​2782 passed​, ​of 2782​
```

**Review by jsumners — APPROVED** [review]
Looks good to me.

**Comment by jsumners** [comment]
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.
